apiVersion: apps/v1
kind: Deployment
metadata:
   name: react1
   labels: 
      app: react1

spec:
   selector:
      matchLabels:
         app: react1
   replicas: 2
   template:
      metadata:
         name: react1
         labels:
            app: react1
      spec:
         containers:
          - name: imedapp
            image: imed1/react-app
            ports:
              - containerPort: 5555
---
apiVersion: v1
kind: Service 
metadata: 
   name: react-service1 
spec:
   type: LoadBalancer
   selector:
       app: react1
   ports:
      - protocol: TCP
        port: 80
        targetPort: 5555
        nodePort: 31003


   
           
            
   
